/**
 * Standalone static filters: the full liquid-glass SVG filter for a border
 * radius, without attaching a controller to an element.

 * @module static-filter
 */

import type {CornerRadii, LiquidGlassOptions} from './types';
import {DEFAULT_OPTIONS, resolveOptions} from './options';
import {getTiles} from './cache';
import {displacementScale, GlassFilterNode} from './filter';
import {sanitizeFilterId} from './geometry';

/** A static filter generated by {@link createFilter}. */
export interface StaticFilter {
	/** DOM id of the generated `<filter>` element. */
	readonly id: string;
	/** `url(#id)` — ready for `backdrop-filter` / `filter`. */
	readonly url: string;
	/** The generated `<filter>` element (lives in the hidden defs host;
	 * detached once {@link StaticFilter.destroy} is called). */
	readonly element: SVGFilterElement;
	/** Largest displacement magnitude in px. */
	readonly maxDisplacement: number;
	/**
	 * Re-position the tiles for a new element size (pure attribute
	 * updates — no re-bake). Safe to call every animation frame.
	 */
	layout(width: number, height: number): void;
	/** Remove the `<filter>` from the DOM. */
	destroy(): void;
}

/** Parameters for {@link createFilter}. */
export interface CreateFilterParams {
	/** Resolved per-corner radii. */
	radii?: CornerRadii;
	/** Shorthand uniform radius (px). */
	borderRadius?: number;
	/** Element width the filter is laid out for (px). Default 200. */
	width?: number;
	/** Element height the filter is laid out for (px). Default 200. */
	height?: number;
	/** Option overrides (same options as {@link create}). */
	options?: LiquidGlassOptions;
}

let staticUid = 0;

/**
 * Generate a static liquid-glass SVG `<filter>` for a border radius —
 * no element controller, no observers. The filter is appended to the
 * hidden defs host and referenced from CSS:
 *
 * ```ts
 * import { createFilter } from 'liquid-glass';
 *
 * const f = createFilter({ borderRadius: 28, width: 420, height: 56 });
 * el.style.backdropFilter = f.url; // Chromium: full refraction
 * f.layout(480, 64);               // cheap re-layout for a new size
 * f.destroy();                     // remove the <filter> from the DOM
 * ```
 *
 * Tiles come from the same cache the element controllers use, so identical
 * geometries share bakes. They are size-independent — `layout` re-positions
 * them for new sizes without re-baking. Note that SVG filters referenced
 * from `backdrop-filter` only work in Chromium; referenced from a regular
 * `filter` they work anywhere SVG filters do.
 *
 * If `options.filterId` is given it becomes the DOM id (sanitized) — pass a
 * unique value per filter unless the geometry and options are identical and
 * sharing is intended.
 *
 * @throws {Error} If neither `radii` nor `borderRadius` is given.
 */
export function createFilter(params: CreateFilterParams): StaticFilter {
	const {radii, borderRadius, width = 200, height = 200, options} = params;
	const o = resolveOptions(DEFAULT_OPTIONS, options);
	const base = typeof borderRadius === 'number' ? {rx: borderRadius, ry: borderRadius} : null;
	const rr = base ? {tl: base, tr: base, br: base, bl: base} : radii;
	if (!rr) throw new Error('createFilter: radii or borderRadius required');

	const tiles = getTiles(rr, o, width, height);
	const id = sanitizeFilterId(options?.filterId ?? null) ?? 'liquid-glass-static-' + ++staticUid;
	const node = new GlassFilterNode();
	node.build(id, tiles, width, height, {
		blur: o.blur,
		scale: displacementScale(tiles.maxDisplacement, o.scale),
		saturate: o.saturate,
		rimSaturation: o.specular.saturation,
		rimOpacity: o.specular.opacity,
	});
	const element = node.element!;
	return {
		id,
		url: 'url(#' + id + ')',
		element,
		maxDisplacement: tiles.maxDisplacement,
		layout(w, h) {
			node.layout(w, h);
		},
		destroy() {
			node.remove();
		},
	};
}
